# Generated by Django 5.0.4 on 2024-04-13 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generator",
            options={"ordering": ("-created_at",)},
        ),
    ]
